# name: ferro_VAE
# channels:
#   - conda-forge
# dependencies:
#   # add your dependencies below
#   # pinning versions if necessary 
#   - python
#   - numpy
#   - scipy
#   - h5py
  

#   # additionally, include these deps
  
#   - ipywidgets
#   - matplotlib
#   - ipympl
#   - jupyterlab
#   - jupyterlab-myst
#   - 'nodejs>=20,<21'
#   - mystmd
#   - pip
#   - pip:
#       - git+https://github.com/pycroscopy/atomai


name: ferro_VAE
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - h5py
  - ipywidgets
  - matplotlib
  - ipympl
  - jupyterlab
  - jupyterlab-myst
  - 'nodejs>=20,<21'
  - mystmd
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - seaborn
  - pip:
      - git+https://github.com/pycroscopy/atomai
      - git+https://github.com/ziatdinovmax/pyroVED@main


